### ISSUE TITLE
Error with character search and search via Char.

### ISSUE THREAD

**Issue by CaH4oyc4568** [drizzle-mizzle/CharacterAI-Discord-Bot#38] opened 2023-03-08 11:28 UTC
Error with character search and search via Char. When using the ai find and ai set commands, the forbidden error appears. I don't understand what the problem is? Is it related somehow to Character Ai?
![image](https://user-images.githubusercontent.com/72382950/223701889-ad2d9738-cde9-402f-b3c2-58f7f69f0322.png)
![Screenshot_2023-03-08-14-28-00-084_com discord-edit](https://user-images.githubusercontent.com/72382950/223701937-ac712481-9db4-4cb9-9531-217f64c42e01.jpg)

**Comment by drizzle-mizzle** [comment] 2023-03-09 01:10
I suppose, you've just set wrong auth token

**Comment by drizzle-mizzle** [comment] 2023-03-09 01:11
Либо у тебя та же проблема, что и в #28

**Comment by CaH4oyc4568** [comment] 2023-03-09 08:50
> I suppose, you just set wrong auth token

![image](https://user-images.githubusercontent.com/72382950/223969506-ff02fee7-a97a-4cc2-917b-5b33b3113e52.png)

**Comment by CaH4oyc4568** [comment] 2023-03-09 08:57
> I suppose, you just set wrong auth token

![IMG_20230309_115645](https://user-images.githubusercontent.com/72382950/223971196-482b6227-9d20-4d46-86a0-f6416691c615.png)

**Comment by drizzle-mizzle** [comment] 2023-03-09 19:37
@CaH4oyc4568 
I think, that's the duplicate of this problem then #28
Sorry, but right now there's no solution but to use it on linux, as still I don't know what causes it.

**Closed by drizzle-mizzle** 2023-03-09 19:37 UTC

**Comment by CaH4oyc4568** [comment] 2023-03-09 20:21
Okay, thanks for trying to help! I will be waiting for updates and news
